### ISSUE TITLE
[codemod][new] vuejs - migration from 2 -> 3

### ISSUE THREAD

**Issue by arshcodemod** [codemod-com/codemod#910]
### Migration details
[[Link to upgrade guide](https://v3-migration.vuejs.org/)]

- [ ] codemod-appinitialization - [[Codemod Studio Link](https://go.codemod.com/7xr0Srp)]
- [ ] codemod-globaltoinstanceAPIs - [[Codemod Studio Link](https://go.codemod.com/hEP6r0E)]
- [ ] codemod-functionalcomponent - [[Codemod Studio Link](https://go.codemod.com/0LbYCyg)]
- [ ] codemod-lifecyclehooks - [[Codemod Studio Link](https://go.codemod.com/QlcRjxk)]
- [ ] codemod-customhooks - [[Codemod Studio Link](https://go.codemod.com/oFrqD67)]
- [ ] codemod-filters - [[Codemod Studio Link](https://go.codemod.com/KCbcnhV)]

----
To contributors working on this task:

- [ ] **Framework Expert**:  For each codemod use case in this migration, provide the Codemod Studio link ([example](https://go.codemod.com/sme-input)) with detailed specifications. Include before/after pairs, transformation logic in comments, and edge cases. Even if the transformation is tricky, provide instructions on detecting the patterns. This helps estimate the effort needed and guides developers to the areas requiring manual changes.

- [ ] **Codemod Creator**: [Build](https://go.codemod.com/build-codemod-docs) and [publish](https://go.codemod.com/codemod-publish-doc) quality codemods that handle most edge cases. False negatives are acceptable, but there should be no false positives. Even if the transformation is tricky, build a codemod that can detect and add comments to guide developers to the areas needing manual changes.

- Questions? -> [Community](https://go.codemod.com/community)

**Comment by Saeid-Za** [comment]
Hello There!
Thank you for starting this tracking issue. I believe there are some helpful tools that could serve as a reference.
- [vue-migration](https://github.com/bippan1407/vue-migration): A tool based on [vue-codemod](https://github.com/vuejs/vue-codemod) to migrate vue 2 to vue 3 (script setup)
- [vue-upgrade-tool](https://github.com/UnrefinedBrain/vue-upgrade-tool) - A codemod built on [vue-metamorph](https://github.com/UnrefinedBrain/vue-metamorph) to upgrade Vue 2 projects to Vue 3 (defineComponent or normal script style)

There are also other repositories, one that I used some years ago but couldn't find unfortunately. 

I'd also suggest that setting the output target to [`script setup`](https://vuejs.org/api/sfc-script-setup) instead of `normal script` style.

One question that I have, is there a preference between `jscodeshift` and `ts-moph` as the engine?
I've used `ts-morph` before, but have never worked with `jscodeshift`.

**Comment by sadeghbarati** [comment]
@Saeid-Za @epr3

Sry for the noise 

https://github.com/sadeghbarati/vue-2-and-3

Created a project that contains Vue 2.7 and 3.4 in the same Vite project so that the Codmod team could test their codemods on it
Feel free to add some if guys **have time** or **interested** already invited as Collaborators in that repository


### vue2.7
- Option API component
- Option API component with Mixins


### vue3.4
- Composition API components (script setup)
- Composition API components with Composables


---


`vue2.7/migrations/v-model.vue` has a bug, I don't remember how we used custom v-model or v-model:title or title.sync in Vue 2, even after reading migration, I couldn't fix that problem xd

**Comment by mohab-sameh** [comment]
> One question that I have, is there a preference between jscodeshift and ts-moph as the engine?

@Saeid-Za `ts-morph` is more powerful in general, but `jscodeshift` has the benefit of being supported by [Codemod Studio](https://go.codemod.com/studio)'s AI, making building codemods with it a much easier process.

**Comment by Saeid-Za** [comment]
Hello there! 👋

There seems to be some confusion regarding the scope of the [migration](https://github.com/sadeghbarati/vue-2-and-3) project, should we provide only the Vue 2 code examples and their corresponding Vue 3 examples for the codemod team, or should we also write the transformers with the help of the studio before handing everything over for integration into a package?

**Comment by sadeghbarati** [comment]
@arshcodemod @alexbit-codemod 👆 🙏

**Comment by mohab-sameh** [comment]
@Saeid-Za If you haven't, can you please join the [Slack community](https://go.codemod.com/community) and ping me there? We have a shared channel for vue upgrade there. @arshcodemod and I will draft a notion doc so we can collaboratively collect data about the migration steps required.

> There seems to be some confusion regarding the scope of the [migration](https://github.com/sadeghbarati/vue-2-and-3) project, should we provide only the Vue 2 code examples and their corresponding Vue 3 examples for the codemod team, or should we also write the transformers with the help of the studio before handing everything over for integration into a package?

Either one is a great contribution. If you would like to provide information and context about the vue upgrade steps, and we take it from there, that's great. Let's collect all the info we'll need to build the codemods together on Notion.

**Comment by arshcodemod** [comment]
@Saeid-Za https://www.notion.so/codemod/Vue-codemods-0a09e6534f9b4aa6a9a076b4305a26f6 taking this discussion to the notion doc here.

We can add in the information here.
