### ISSUE TITLE
[codemod][issue] MSW v2 - issue with arrow function shorthand and delay

### ISSUE THREAD

**Issue by Retsam** [codemod-com/codemod#916]
### Faulty codemod

`msw/2/response-usages` -> [codemod source to be updated](https://github.com/codemod-com/codemod/tree/main/packages/codemods/msw/2/response-usages)

### Code before transformation

```jsx
import { http } from "msw";

const handler = http.post("/url", (_req, res, ctx) => (
    res(ctx.delay(3000), ctx.json({})),
);

```

### Expected code after transformation

```jsx
import { http, delay, HttpResponse } from "msw";

const handler = http.post("/url", async (_req, res, ctx) => {
    await delay(3000);
    return HttpResponse.json({});
});
```

### Actual code after transformation

Fails to transform.

Though if I wrap my arrow function shorthand into a body with a return statement, I get this output instead:

```jsx
import { http, delay, HttpResponse } from "msw";

const handler = http.post("/url", (_req, res, ctx) => {
    return HttpResponse.json({});
});
```
(which is almost correct, but missing the `delay(3000)` statement and the async function marker.

### Estimated severity

Medium?  It seems like it's a fairly small tweak: if the callback has an expression body, replace it with a block body before continuing, but I couldn't find a good way to do that without breaking all the existing 'handles'.   Maybe it would need to happen as a separate pass before the rest of the codemod - either targetted (look for the usage of 'delay'), or just a general pass that gets rid of the shorthand syntax for msw callbacks.

### Environment:

-   Codemod CLI version: 0.11.17
-   OS: MacOS 14.5
-   Node.js version: v20.14.0

### Additional context

Add any other context about the problem here. This might include the target project, explanation of faulty output related to business logic, relevant links, etc.

**Comment by alexbit-codemod** [comment]
Thanks for reporting this, @Retsam, and for providing all the details. 

Just to better understand the impact and priority of this issue, off the top of your head, could you tell me the FP (False Positive) and FN (False Negative) rates for this MSW codemod? 
For example, the recipe:

1. Change 100 files
2. Missed transforming 2 files (reported here)
3. Mistakenly transformed 0 files

Also, have you already completed this migration and handled the FNs manually, or do you want to see this issue fixed while dealing with larger migration you're working on?

**Comment by Retsam** [comment]
In my case I have 6 MSW files (with about 50 different endpoints mocked):

1.  Three of them failed to transform due to having at least one case of this pattern; with about cases overall.  
2. After fixing those 10 cases, all the files transformed, but I'm pretty sure all usages of `ctx.delay` were lost.  I probably had at least one example in every file, so on a file basis probably 100% false positive, technically, maybe a 30% on a per MSW endpoint basis.  (Which would vary a lot from codebase to codebase; I imagine some people put a delay on basically every endpoint they mock, and some people don't use it at all)

The second isn't a dealbreaker; would still rather put the delays back manually (or just lose them) than migrate all this manually, but would be good to fix.

**Comment by alexbit-codemod** [comment]
This context is really helpful, thank you! Just to confirm, can I summarize it like this:

1. The current codemod has **false negatives**—it doesn't detect certain patterns but doesn't break them, so users have to handle them manually. In your case, this affected 10 out of 50 instances (20%).
2. Instead of manually migrating just those 10 instances, you opted to **wrap** all arrow function shorthands (not just those 10) into a body with a return statement. The codemod then transformed them, but **now there are false positives**.
3. You still prefer this approach of wrapping and handling `ctx.delay` manually over manually transforming all 10 instances. 

The ideal fix here (mostly for future devs, although you could benefit from this a little bit too) is to **address the initial false negative issue** (rather than the false positives that occurred after your wrapping).

If I got this correctly, then this codemod's automation coverage is 80%. by fixing it, we might get close to 100%.

I think we have more than enough context to prioritize this task.

**Comment by r4zendev** [comment]
Closing as per https://github.com/codemod-com/codemod/issues/917#issuecomment-2225421874
